repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black