MYCA_GENERIC_PROMPT_TEMPLATE = (
    "You are given below a description of the tasks and goals in my todo list. "
    "Always answer the query using the provided context information, "
    "and not prior knowledge.\n"
    "Some rules to follow:\n"
    "1. Never directly reference the given context in your answer.\n"
    "2. Avoid statements like 'Based on the context, ...' or "
    "'The context information ...' or anything along "
    "those lines.\n"
    "Context information is below.\n"
    "---------------------\n"
    "{context_str}\n"
    "---------------------\n"
    "Given the context information, "
    "answer the query.\n"
    "Query: {query}\n"
    "Answer: "
)


MYCA_NEW_USER_PEPTALK_PROMPT_TEMPLATE = (
    "You are given below a description of the tasks and goals in my todo list. "
    "Always answer the query using the provided context information, "
    "and not prior knowledge.\n"
    "Some rules to follow:\n"
    "1. Never directly reference the given context in your answer.\n"
    "2. Avoid statements like 'Based on the context, ...' or "
    "'The context information ...' or anything along "
    "those lines.\n"
    "Context information is below.\n"
    "---------------------\n"
    "{context_str}\n"
    "---------------------\n"
    "Given the context information, "
    "answer the query.\n"
    "Query: {query}\n"
    "Answer: "
)


MYCA_PEPTALK_PROMPT_TEMPLATE = (
    "You are given a list of tasks and task groups of my todo list. "
    "Based on these tasks and task groups, answer a question for me."
    "Always answer the query using the provided context information, "
    "and 'not prior knowledge.\n"
    "Some rules to follow:\n"
    "1. Avoid statements like 'Based on the context, ...' or "
    "'The context information ...' or anything along "
    "those lines.\n"
    "Context information is below.\n"
    "---------------------\n"
    "Below are a list of documents describing each task and task group in the user's todo list and their properties.\n"
    "{context_str}\n"
    "---------------------\n"
    "Given the context information, "
    "answer the query.\n"
    "Query: {query}\n"
    "Answer: "
)
